version: '3.8'

services:
  owlistic:
    # image: ghcr.io/owlistic-notes/owlistic:0.1.0
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-arm64}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - nats
    environment:
      - APP_ORIGINS=http://localhost*,http://owlistic*,http://owlistic-app*
      - BROKER_ADDRESS=nats:4222
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=postgres
    networks:
      - server
      - events
      - db

  owlistic-app:
    # image: ghcr.io/owlistic-notes/owlistic-app:0.1.0
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-arm64}
    ports:
      - "80:80"
    depends_on:
      - owlistic

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db

  nats:
    image: nats
    command:
      - --http_port
      - "8222"
      - -js
      - -sd
      - /var/lib/nats/data
    ports:
     - "4222:4222"
     - "8222:8222"
    volumes:
      - nats_data:/var/lib/nats/data
    networks:
      - events

volumes:
  postgres_data:
  nats_data:

networks:
  server:
    driver: bridge
  events:
    driver: bridge
  db:
    driver: bridge