version: '3.8'

services:
  owlistic:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-arm64}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - APP_ORIGINS=http://owlistic*,http://owlistic-app*
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=postgres
      - KAFKA_BROKER=kafka:9092
    networks:
      - owlistic

  owlistic-app:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-arm64}
    ports:
      - "80:80"
    depends_on:
      - owlistic
    networks:
      - owlistic

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - owlistic

  kafka:
    image: bitnami/kafka:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - owlistic

  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
    networks:
      - owlistic

volumes:
  postgres_data:

networks:
  owlistic:
    driver: bridge