name: thinkstack
description: A productivity app built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  go_router: ^13.1.0
  flutter_markdown: ^0.6.18
  sqflite: ^2.3.2
  path: ^1.8.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  logging: ^1.3.0
  web_socket_channel: ^3.0.2
  super_editor: ^0.3.0-dev.23
  attributed_text: ^0.4.4
  shared_preferences: ^2.5.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
